import { ResumeData } from '../types/resume';

export const sampleResume: ResumeData = {
  personal: {
    fullName: "DOEM MONGHOUT",
    koreanName: "돔 몽하웃",
    photoUrl: "/photo.jpg",
    jobTitle: "Manufacturing & Production Specialist (제조업 및 생산 라인 전문 인력)",
    email: "doem.monghout94@gmail.com",
    phone: "010-4373-4343",
    dateOfBirth: "1994-11-10",
    gender: "Male",
    nationality: "Cambodia (캄보디아)",
    currentAddress: "전라북도 군산시 군산산단로 146-25 (오식도동, 비엔디티 코리아)",
    height: "179 cm",
    weight: "74 kg",
  },
  visa: {
    visaType: "E-9 (Non-professional Employment)",
    visaExpiryDate: "2027-02-26",
    sponsorshipNeeded: false,
    arcStatus: "Registered (ARC)",
    availability: "Immediately (즉시 입사 가능)",
    desiredEmploymentType: "Full-time (정규직 / 계약직)",
    desiredLocation: "Jeonbuk / Gunsan / Any in Korea (전북 / 군산 / 전국)",
  },
  summary: "우수한 체격 조건(179cm, 74kg)과 성실한 근태를 바탕으로 전북 군산 산단 현장에서 3년 이상 차질 없이 근무 중인 캄보디아 출신 비전문취업(E-9) 현장 전문 인재입니다. 2027년 2월까지 합법적 체류 및 근무 자격을 소지하고 있으며, 제조 라인 설비 가공, 중량물 운범, 제품 정밀 조립 및 무재해 안전 규칙 준수가 뛰어납니다.",
  languages: [
    {
      id: "lang-1",
      language: "Korean (한국어)",
      proficiency: "Workplace & Production Communication / 현장 작업 지시 이행 능숙",
      testScore: "EPS-TOPIK (한국어능력시험 합격)",
    },
    {
      id: "lang-2",
      language: "Khmer / Cambodian (캄보디아어)",
      proficiency: "Native / 모국어",
      testScore: "Native Speaker",
    },
    {
      id: "lang-3",
      language: "English (영어)",
      proficiency: "Basic / 기초 회화",
      testScore: "Basic",
    },
  ],
  experiences: [
    {
      id: "exp-1",
      company: "비엔디티 코리아 (BNDT Korea - 군산 오식도동 산단)",
      location: "Jeollabuk-do, Gunsan-si (전북 군산시 군산산단로)",
      role: "Manufacturing & Production Specialist (생산 라인 및 설비 가공)",
      startDate: "2022-05",
      endDate: "Present",
      isCurrent: true,
      description: "• 산단 제조 라인 기계 설비 가공, 부품 조립 및 정밀 검수/포장\n• 현장 안전 수칙 100% 이행 및 생산 목표 수량 차질 없이 적기 달성\n• 한국어 작업 지시 명확한 이행 및 군산 산단 현장 근로자 간 뛰어난 협업",
    },
  ],
  education: [
    {
      id: "edu-1",
      institution: "General High School (Takeo, Cambodia)",
      location: "Takeo, Cambodia",
      degree: "High School Diploma (고등학교 졸업)",
      major: "General Education",
      startDate: "2009-10",
      endDate: "2012-07",
      gpa: "Graduated",
    },
  ],
  skills: [
    "Manufacturing & Industrial Line Operation (제조/생산 라인)",
    "Facility Operation & Heavy Equipment (설비 가공 및 중량물 운범)",
    "Quality Inspection & Packaging (품질 검수 및 적재/포장)",
    "EPS-TOPIK Workplace Korean (현장 한국어 소통)",
    "Excellent Physical Condition (우수한 신체 피지컬 179cm/74kg)",
    "Team Cooperation & Safety Rules (팀워크 및 무재해 규칙 준수)",
  ],
  certifications: [
    {
      id: "cert-1",
      title: "Republic of Korea E-9 Working Visa & Residence Registration Card",
      issuer: "Gunsan Branch, Jeonju Immigration Office (전주출입국·외국인사무소 군산출장소장)",
      issueDate: "2022-05",
    },
    {
      id: "cert-2",
      title: "EPS-TOPIK (Employment Permit System Test of Proficiency in Korean)",
      issuer: "HRD Korea (한국산업인력공단)",
      issueDate: "2022-03",
    },
  ],
};

export const emptyResume: ResumeData = {
  personal: {
    fullName: "",
    koreanName: "",
    photoUrl: "",
    jobTitle: "",
    email: "",
    phone: "",
    dateOfBirth: "",
    gender: "",
    nationality: "",
    currentAddress: "",
    height: "",
    weight: "",
  },
  visa: {
    visaType: "E-9 (Non-professional Employment)",
    visaExpiryDate: "",
    sponsorshipNeeded: false,
    arcStatus: "Registered (ARC)",
    availability: "Immediately",
    desiredEmploymentType: "Full-time",
    desiredLocation: "Korea",
  },
  summary: "",
  languages: [
    {
      id: "lang-default-1",
      language: "Korean (한국어)",
      proficiency: "Workplace Communication",
      testScore: "EPS-TOPIK",
    },
    {
      id: "lang-default-2",
      language: "Khmer / Cambodian",
      proficiency: "Native",
      testScore: "Native",
    },
  ],
  experiences: [
    {
      id: "exp-default-1",
      company: "",
      location: "",
      role: "",
      startDate: "",
      endDate: "",
      isCurrent: false,
      description: "",
    },
  ],
  education: [
    {
      id: "edu-default-1",
      institution: "",
      location: "",
      degree: "High School / Bachelor's",
      major: "",
      startDate: "",
      endDate: "",
      gpa: "",
    },
  ],
  skills: ["Manufacturing", "Quality Control"],
  certifications: [],
};
