import { ResumeData } from '../types/resume';

export const sampleResume: ResumeData = {
  personal: {
    fullName: "NIL SOPHEARA",
    koreanName: "닐 소피아라",
    photoUrl: "/photo.jpg",
    jobTitle: "Manufacturing & Production Specialist (제조업 및 생산 라인 전문 인력)",
    email: "nil.sopheara90@gmail.com",
    phone: "010-9614-7748",
    dateOfBirth: "1990-08-07",
    gender: "Male",
    nationality: "Cambodia (캄보디아)",
    currentAddress: "충청남도 천안시 동남구 풍세면 돈마루1길 177-23 (우림빌 402호)",
    height: "165 cm",
    weight: "63 kg",
  },
  visa: {
    visaType: "E-9 (Non-professional Employment)",
    visaExpiryDate: "2027-09-16",
    sponsorshipNeeded: false,
    arcStatus: "Registered (ARC)",
    availability: "Immediately (즉시 입사 가능)",
    desiredEmploymentType: "Full-time (정규직 / 계약직)",
    desiredLocation: "Chungnam / Cheonan / Any in Korea (충남 / 천안 / 전국)",
  },
  summary: "풍부한 현장 경험과 우수한 근태를 갖춘 캄보디아 출신 비전문취업(E-9) 현장 인재입니다. 2027년 9월까지 합법적 체류 및 근무 자격을 소지하고 있으며, 165cm / 63kg의 민첩하고 안정적인 체력으로 제조 라인 설비 가공, 부품 정밀 조립, 품질 검수 및 제품 포장 작업을 충실히 수행합니다. 한국어 작업 지시 및 현장 안전 수칙 이수가 뛰어납니다.",
  languages: [
    {
      id: "lang-1",
      language: "Korean (한국어)",
      proficiency: "Workplace & Production Communication / 현장 작업 지시 이행 능숙",
      testScore: "EPS-TOPIK (한국어능력시험 합격)",
    },
    {
      id: "lang-2",
      language: "Khmer / Cambodian (캄보디아어)",
      proficiency: "Native / 모국어",
      testScore: "Native Speaker",
    },
    {
      id: "lang-3",
      language: "English (영어)",
      proficiency: "Basic / 기초 회화",
      testScore: "Basic",
    },
  ],
  experiences: [
    {
      id: "exp-1",
      company: "천안 제조업체 (Cheonan Manufacturing Plant)",
      location: "Chungcheongnam-do, Cheonan-si (충남 천안시 동남구)",
      role: "Manufacturing & Assembly Specialist (생산 라인 및 설비 가공)",
      startDate: "2023-01",
      endDate: "Present",
      isCurrent: true,
      description: "• 제조 설비 가공 라인 운용, 완제품 품질 검수 및 포장/적재 작업 수행\n• 작업장 안전 규정 100% 이행 및 생산 무재해 달성\n• 한국어 현장 작업 지시 이행 및 협력적인 팀워크 수행",
    },
  ],
  education: [
    {
      id: "edu-1",
      institution: "General High School (Kandal, Cambodia)",
      location: "Kandal, Cambodia",
      degree: "High School Diploma (고등학교 졸업)",
      major: "General Education",
      startDate: "2005-10",
      endDate: "2008-07",
      gpa: "Graduated",
    },
  ],
  skills: [
    "Manufacturing & Production Line Assembly (제조/생산 라인)",
    "Facility Operation & Safety Regulations (설비 가공 및 안전 관리)",
    "Quality Inspection & Packaging (품질 검수 및 포장)",
    "EPS-TOPIK Workplace Korean (현장 한국어 소통)",
    "Strong Diligence & Stamina (성실함 & 체력 165cm/63kg)",
    "Teamwork & Safety Compliance (팀워크 및 작업 지시 이행)",
  ],
  certifications: [
    {
      id: "cert-1",
      title: "Republic of Korea E-9 Working Visa & Residence Registration Card",
      issuer: "Goyang & Seoul Immigration Office (양주출입국·외국인사무소 고양출장소장)",
      issueDate: "2023-01",
    },
    {
      id: "cert-2",
      title: "EPS-TOPIK (Employment Permit System Test of Proficiency in Korean)",
      issuer: "HRD Korea (한국산업인력공단)",
      issueDate: "2022-11",
    },
  ],
};

export const emptyResume: ResumeData = {
  personal: {
    fullName: "",
    koreanName: "",
    photoUrl: "",
    jobTitle: "",
    email: "",
    phone: "",
    dateOfBirth: "",
    gender: "",
    nationality: "",
    currentAddress: "",
    height: "",
    weight: "",
  },
  visa: {
    visaType: "E-9 (Non-professional Employment)",
    visaExpiryDate: "",
    sponsorshipNeeded: false,
    arcStatus: "Registered (ARC)",
    availability: "Immediately",
    desiredEmploymentType: "Full-time",
    desiredLocation: "Korea",
  },
  summary: "",
  languages: [
    {
      id: "lang-default-1",
      language: "Korean (한국어)",
      proficiency: "Workplace Communication",
      testScore: "EPS-TOPIK",
    },
    {
      id: "lang-default-2",
      language: "Khmer / Cambodian",
      proficiency: "Native",
      testScore: "Native",
    },
  ],
  experiences: [
    {
      id: "exp-default-1",
      company: "",
      location: "",
      role: "",
      startDate: "",
      endDate: "",
      isCurrent: false,
      description: "",
    },
  ],
  education: [
    {
      id: "edu-default-1",
      institution: "",
      location: "",
      degree: "High School / Bachelor's",
      major: "",
      startDate: "",
      endDate: "",
      gpa: "",
    },
  ],
  skills: ["Manufacturing", "Quality Control"],
  certifications: [],
};
