import { ResumeData } from '../types/resume';

export const sampleResume: ResumeData = {
  personal: {
    fullName: "Alexandre Tremblay",
    koreanName: "알렉스 (Alex)",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    jobTitle: "Senior Full-Stack & AI Solutions Developer",
    email: "alex.tremblay.dev@gmail.com",
    phone: "+82 10-8234-5678",
    dateOfBirth: "1994-08-15",
    gender: "Male",
    nationality: "Canada",
    currentAddress: "Mapo-gu, Seoul, Republic of Korea",
  },
  visa: {
    visaType: "E-7-1 (Special Activity / Professional)",
    visaExpiryDate: "2027-10-31",
    sponsorshipNeeded: false,
    arcStatus: "Registered (ARC)",
    availability: "Immediately (Within 2 Weeks)",
    desiredEmploymentType: "Full-time",
    desiredLocation: "Seoul / Pangyo / Remote",
  },
  summary: "Multilingual Full-Stack Developer with 6+ years of experience building scalable web applications and enterprise platforms. Graduated with a Master\'s in Computer Science from Seoul National University. Fluent in Korean (TOPIK Level 5) with hands-on experience leading cross-cultural engineering teams in fast-paced Korean IT environments. Legally authorized to work in Korea under an E-7 visa status with no immediate sponsorship required.",
  languages: [
    {
      id: "lang-1",
      language: "Korean (한국어)",
      proficiency: "Professional Working / Business Fluent",
      testScore: "TOPIK Level 5 (토픽 5급)",
    },
    {
      id: "lang-2",
      language: "English",
      proficiency: "Native / Bilingual",
      testScore: "Native Speaker",
    },
    {
      id: "lang-3",
      language: "French (Français)",
      proficiency: "Native / Bilingual",
      testScore: "Native Speaker",
    },
  ],
  experiences: [
    {
      id: "exp-1",
      company: "Kakao Mobility Corp / Global Tech Lab",
      location: "Seongnam-si, Pangyo, Korea",
      role: "Lead Full-Stack Engineer",
      startDate: "2022-03",
      endDate: "Present",
      isCurrent: true,
      description: "• Architected and deployed a multi-region dispatch optimization platform processing 1.2M+ daily requests using Next.js, Node.js, and Redis.\n• Led a bilingual squad of 7 engineers (Korean & international talent), boosting cross-border sprint velocity by 35%.\n• Optimized database query pipelines, cutting p99 server response time from 380ms down to 110ms.",
    },
    {
      id: "exp-2",
      company: "Seoul AI Partners Inc.",
      location: "Gangnam-gu, Seoul, Korea",
      role: "Full-Stack Software Engineer",
      startDate: "2020-09",
      endDate: "2022-02",
      isCurrent: false,
      description: "• Developed interactive customer dashboard interfaces using React, TypeScript, and Tailwind CSS.\n• Integrated REST and GraphQL APIs for real-time LLM-driven recommendation microservices.\n• Collaborated closely with Korean product managers, participating in 100% Korean sprint planning and tech reviews.",
    },
    {
      id: "exp-3",
      company: "Shopify",
      location: "Toronto, Ontario, Canada",
      role: "Software Developer Intern",
      startDate: "2018-05",
      endDate: "2019-08",
      isCurrent: false,
      description: "• Built automated merchant onboarding UI workflows, increasing checkout conversion rates by 4.2%.\n• Wrote end-to-end integration and unit tests achieving 92% code coverage.",
    },
  ],
  education: [
    {
      id: "edu-1",
      institution: "Seoul National University (서울대학교)",
      location: "Seoul, Republic of Korea",
      degree: "Master of Science (M.S.)",
      major: "Computer Science & Engineering",
      startDate: "2019-09",
      endDate: "2021-08",
      gpa: "3.92 / 4.3",
    },
    {
      id: "edu-2",
      institution: "McGill University",
      location: "Montreal, Quebec, Canada",
      degree: "Bachelor of Science (B.S.)",
      major: "Computer Science",
      startDate: "2014-09",
      endDate: "2018-05",
      gpa: "3.80 / 4.0",
    },
  ],
  skills: [
    "TypeScript",
    "React / Next.js",
    "Node.js",
    "Python",
    "PostgreSQL",
    "AWS / Cloud Architecture",
    "Docker & Kubernetes",
    "Tailwind CSS",
    "Git & CI/CD",
    "Cross-Cultural Team Leadership",
  ],
  certifications: [
    {
      id: "cert-1",
      title: "AWS Certified Solutions Architect – Associate",
      issuer: "Amazon Web Services (AWS)",
      issueDate: "2023-11",
    },
    {
      id: "cert-2",
      title: "Test of Proficiency in Korean (TOPIK II) - Level 5",
      issuer: "National Institute for International Education (NIIED)",
      issueDate: "2021-06",
    },
  ],
};

export const emptyResume: ResumeData = {
  personal: {
    fullName: "",
    koreanName: "",
    photoUrl: "",
    jobTitle: "",
    email: "",
    phone: "",
    dateOfBirth: "",
    gender: "",
    nationality: "",
    currentAddress: "",
  },
  visa: {
    visaType: "E-7",
    visaExpiryDate: "",
    sponsorshipNeeded: false,
    arcStatus: "Registered (ARC)",
    availability: "Immediately",
    desiredEmploymentType: "Full-time",
    desiredLocation: "Seoul, Korea",
  },
  summary: "",
  languages: [
    {
      id: "lang-default-1",
      language: "Korean (한국어)",
      proficiency: "Business Fluent",
      testScore: "TOPIK Level 4",
    },
    {
      id: "lang-default-2",
      language: "English",
      proficiency: "Native / Bilingual",
      testScore: "",
    },
  ],
  experiences: [
    {
      id: "exp-default-1",
      company: "",
      location: "",
      role: "",
      startDate: "",
      endDate: "",
      isCurrent: false,
      description: "",
    },
  ],
  education: [
    {
      id: "edu-default-1",
      institution: "",
      location: "",
      degree: "Bachelor's Degree",
      major: "",
      startDate: "",
      endDate: "",
      gpa: "",
    },
  ],
  skills: ["Communication", "Problem Solving"],
  certifications: [],
};
